### ISSUE TITLE
大佬请问OAID里面的ASSET_FILE_NAME_CERT是要去申请的吗？

### ISSUE THREAD

**Issue by Wen-Guoguo** [yatyricky/yatyricky.github.io#2]
ASSET_FILE_NAME_CERT 是要去移动联盟申请，还是直接用自己的包名就行呢

**Comment by yatyricky** [comment]
不清楚，我们也在研究，先上1.0.25吧，没时间折腾这玩意，顶多就是投放数据不准。
另外到正确的地方 https://github.com/2tu/msa 去提问。
